FROM ubuntu:16.04
MAINTAINER Nicolas Giard, nicolas.giard@coaxys.com

RUN apt-get update
RUN apt-get -y install software-properties-common python-software-properties curl wget unzip
RUN apt-get clean && apt-get autoremove
